repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length=85]
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/PyCQA/prospector
    rev: 1.3.1
    hooks:
    - id: prospector
      args: [--uses=flask, --strictness=high]
